<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pramesh" failures="1" tests="1" name="Test_Scenario_2" time="46.334" errors="0" timestamp="2024-10-18T11:18:44 IST">
  <testcase classname="testcases.TestScenario1_LTAdvanced_Certification" name="lambdaTest_AdvancedCertification" time="33.943">
    <failure type="java.lang.AssertionError" message="expected [https://community.lambdatest.com/] but found [https://www.lambdatest.com/blog/]">
      <![CDATA[java.lang.AssertionError: expected [https://community.lambdatest.com/] but found [https://www.lambdatest.com/blog/]
at pageclasses.CommunityPage.validateTitle_inCommunityPage(CommunityPage.java:37)
at testcases.TestScenario1_LTAdvanced_Certification.lambdaTest_AdvancedCertification(TestScenario1_LTAdvanced_Certification.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- lambdaTest_AdvancedCertification -->
</testsuite> <!-- Test_Scenario_2 -->
