<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pramesh" failures="1" tests="3" name="testcases.TestScenario1_LTAdvanced_Certification" time="289.423" errors="0" timestamp="2024-10-18T11:20:51 IST" skipped="0">
  <testcase classname="testcases.TestScenario1_LTAdvanced_Certification" name="lambdaTest_AdvancedCertification" time="174.371"/>
  <system-out/>
  <testcase classname="testcases.TestScenario1_LTAdvanced_Certification" name="lambdaTest_AdvancedCertification" time="68.776"/>
  <system-out/>
  <testcase classname="testcases.TestScenario1_LTAdvanced_Certification" name="lambdaTest_AdvancedCertification" time="46.276">
    <failure message="expected [https://community.lambdatest.com/] but found [https://www.lambdatest.com/blog/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://community.lambdatest.com/] but found [https://www.lambdatest.com/blog/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at pageclasses.CommunityPage.validateTitle_inCommunityPage(CommunityPage.java:37)
at testcases.TestScenario1_LTAdvanced_Certification.lambdaTest_AdvancedCertification(TestScenario1_LTAdvanced_Certification.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- lambdaTest_AdvancedCertification -->
  <system-out/>
</testsuite> <!-- testcases.TestScenario1_LTAdvanced_Certification -->
